name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run flake8
      run: flake8

    - name: Run mypy
      run: mypy .

    - name: Run tests with pytest
      run: python -m pytest
